# Generated by Django 5.1.6 on 2025-03-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='is_Approved',
            field=models.BooleanField(default=False),
        ),
    ]
